services:
  postgres:
    container_name: "LIBRARY_PG_DATABASE"
    image: 'postgres:16.0-alpine'
    environment:
      - 'POSTGRES_DB=${PG_DB_NAME_PROD}'
      - 'POSTGRES_PASSWORD=${PG_PASSWORD_PROD}'
      - 'POSTGRES_USER=${PG_USERNAME_PROD}'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./src/main/resources/sql/init/docker:/docker-entrypoint-initdb.d
    networks:
      - LibraryBooksNetwork

networks:
  LibraryBooksNetwork:
    driver: bridge
